# Generated by Django 3.2 on 2022-07-27 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_auto_20220719_1603"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categroies"},
        ),
    ]
