# Generated by Django 3.2 on 2022-07-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_has_sizes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_sizes',
            new_name='has_panorama',
        ),
        migrations.AddField(
            model_name='product',
            name='has_rectangle',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
