# Generated by Django 3.2 on 2022-07-27 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220727_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_panorama',
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_rectangle',
        ),
    ]
