# Generated by Django 3.2 on 2022-08-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_auto_20220806_1839"),
    ]

    operations = [
        migrations.AddField(
            model_name="combination",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
