# Generated by Django 3.2 on 2022-08-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='product_type',
            field=models.CharField(blank=True, choices=[('standard', 'standard'), ('panoramic', 'panoramic'), ('3panel', '3panel'), ('5panel', '5panel')], max_length=254, null=True),
        ),
    ]
