# Generated by Django 3.2 on 2022-08-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_combination_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=254),
        ),
    ]
