# Generated by Django 3.2 on 2022-08-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_producttype_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='product_type',
            field=models.CharField(blank=True, choices=[('STANDARD', 'standard'), ('PANORAMIC', 'panoramic'), ('3PANEL', '3panel'), ('5PANEL', '5panel')], max_length=254, null=True),
        ),
    ]
